Revert "Disable `moveit2` source build in CI config"
This reverts commit cc1702187ad71990d78269e241e23a7a649b2b6c.

    rosdep install -y -q -n --from-paths . --ignore-src --rosdistro foxy
    ERROR: the following packages/stacks could not have their rosdep keys resolved
    to system dependencies:
    ur5_moveit_config: Cannot locate rosdep definition for [moveit_simple_controller_manager]
    The command "rosdep install -y -q -n --from-paths . --ignore-src --rosdistro foxy" failed [trial 1 of 3].
    [...]
    The command "rosdep install -y -q -n --from-paths . --ignore-src --rosdistro foxy" failed with error code 1.